### PR TITLE
adding line to trigger rebuild on push to main

### PR DESCRIPTION
**Pull request by egazzarr**

### CODE REVIEW

**Comment by garciagenrique** [comment]
This would create a new container every single time we commit (push or merge) to main. I don't think this is the desired functionality

**Comment by egazzarr** [comment]
I agree that yes it should be a chain reaction logic. It is not imminent, as the urgent one was the client one, which has been successfully rebuilt.

**Comment by garciagenrique** [comment]
Then I'm taking care of the propagation logic asap!

**Comment by garciagenrique** [comment]
What are the EGI trusts anchors exactly used for, btw ?

**Pull request closed without merging**
