### PR TITLE
Flux dashboard

### PR DESCRIPTION
**Pull request by goseind**
Add dashboard for flux with oidc auth for login.
See also: https://docs.gitops.weave.works/docs/open-source/getting-started/install-OSS/

### CODE REVIEW

**Comment by garciagenrique** [comment]
Hi @goseind,
Thanks for the suggestion, looks cool the tool! 
I would also like the opinion of @egazzarr (you can have a general vision of what it does on the quickstart video: https://docs.gitops.weave.works/)
However, our cluster is not that "simple".... meaning that we would need to sync rucio fully again....
On the contrary, it can also be the opportunity of upgrading flux to a stable version (we are currently using a -rc version and v.2.0.1 was just released).

My personal opinion is that I don't want another "layer of simplicity" that adds an immediate "layer of complexity and debugging" until we make everything work again. 

But it the majority agrees, let's adopt the tool!

**Comment by egazzarr** [comment]
Looks good! 
Do we need to change the flux version? I would keep this one as it works well, it seems like!

**Comment by garciagenrique** [comment]
> Looks good! Do we need to change the flux version? I would keep this one as it works well, it seems like!

We don't. Just trying to keep good dev practices as we are deploying everything from zero.

However, I underline again the question; rucio deployment. Are we sure this tool will be able to handle all our cluster ?

**Comment by goseind** [comment]
This is an additional helm chart on top and serves as a dashboard for flux. It can be removed without hard feelings anytime :)

**Pull request merged**
